version: 2
jobs:
  build:
    docker:
      - image: kierdavis/nix-circle:latest
    steps:
      - checkout:
          name: Checkout project source
      - run:
          name: Patch source
          command: |
            # Ensure todonotes package has the 'disable' flag.
            sed --in-place 's,\usepackage{todonotes},\usepackage[disable]{todonotes},' src/setup.tex
      - run:
          name: Build document
          command: nix-build
      - store_artifacts:
          name: Store build artifact
          path: result/cv.pdf
          destination: cv.pdf
